# ------------------------------------------------------------
# GitHub Actions Workflow: Deploy energy data to GitHub Pages
#
# Description:
#   - Runs a Python data pipeline that fetches and processes
#     UK energy generation data (BMRS + NESO).
#   - Saves the output as a CSV file and publishes it to GitHub Pages.
#
# Triggers:
#   - Every 30 minutes (cron schedule).
#   - On push to the main branch.
#   - Manually via workflow_dispatch.
# ------------------------------------------------------------

name: Deploy energy data to GitHub Pages

on:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.6"

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run data script
        run: python fetch_data.py

      # Move processed CSV into public folder for deployment
      - name: Move CSV into output folder
        run: |
          mkdir -p public
          mv data_pipeline/Data/combined_energy_data.csv public/

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
